### ISSUE TITLE
DataTableコンポーネントを作る

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/cuv#112]
https://vuetifyjs.com/en/components/data-tables/basics/

今欲しいもの
* propsで、ページネーションが設定できる refs. https://vuetifyjs.com/en/components/data-tables/pagination/
* propsで、カラムとデータを渡すとテーブル表示できる refs. https://vuetifyjs.com/en/components/data-tables/basics/#v-data-table
* 行の単一/一括選択ができる refs. https://vuetifyjs.com/en/components/data-tables/selection/

**Comment by kbtaniguchi** [comment]
* propsでテーブルデータのフィルタができる

**Comment by kondoriyo** [comment]
マージしたのでcloseします
