### ISSUE TITLE
Form部品: labelが設定されていないときには上下中央にコンテンツが表示されるようにする

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/cuv#127]
label部分に空間があいてしまうのが違和感がある
![Image](https://github.com/actier-luchta/cuv/assets/26402669/f0d0922f-f4a3-4b35-8130-87e841bcb5c9)

Vuetifyのようにlabelがあるときと無いときとでコンテンツの表示位置が自然に上下中央になるように調整したい
![Image](https://github.com/actier-luchta/cuv/assets/26402669/439ba1bb-b57a-4125-ae64-3764eed67959)
![Image](https://github.com/actier-luchta/cuv/assets/26402669/c6b14390-18f4-4bba-9184-1b1d523e924c)

**Comment by kondoriyo** [comment]
対応してマージしたのでcloseします
