### ISSUE TITLE
CCheckbox: 他の部品と比べてラベルの文字が大きい

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/cuv#130]
text-xl, text-baseでcheckboxやlabelのフォントサイズが調整されているが、
他の部品と大きさの平仄が合わなくなる。デフォルトで使っているかぎり、
部品に表示されるテキストは全体の平仄が合うようにしたい

![Image](https://user-images.githubusercontent.com/26402669/241607865-a35f28df-3b70-4a5a-9876-9f0c0a20ebcc.png)

**Comment by kondoriyo** [comment]
対応してマージしたのでcloseします
