### ISSUE TITLE
カラーパレットの色調が足りないので追加する

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/cuv#135]
薄い方（lighten）と濃い方（darken）へのグラデーションがないとまともなデザインが構築できない
https://vuetifyjs.com/en/styles/colors/

色の種類（ex. primary...）はそのままでlighten, darkenのscaleを追加する（ex. primary-lighten-1...）

**Comment by kondoriyo** [comment]
マージしたのでcloseします
