### ISSUE TITLE
Button：variantがoutlineのボタンのborderが太くなっている

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/cuv#162]
![Image](https://user-images.githubusercontent.com/26402669/246734983-22f1c57b-3f76-49ee-af85-6daef7eaddb7.png)

元々はVuetify（下記）と同じぐらいだったと思うので、そちらに戻したい

![Image](https://user-images.githubusercontent.com/26402669/246735136-3da604d5-e173-4557-8f63-1bacd0fe25bf.png)

**Comment by kondoriyo** [comment]
マージしたのでcloseします
