### ISSUE TITLE
TextFiled: readonlyのときはテキストの色を薄くしないほうがよい

### ISSUE THREAD

**Issue by kbtaniguchi** [actier-luchta/cuv#177]
disableのときにテキストの色を薄くするのは良いが、readonlyのときはテキストの色を薄くしない

フォームで登録したデータを見る画面（xx詳細画面など）で、readonlyのTextFiledを使って、
登録フォームと似たような形の画面をレイアウトしたいことがあるが、その場合に全体的にテキストが薄くなってしまうのは見づらいし、readonly以上の含意を感じる
readonlyは「選択しても編集ができない」というだけで、見た目は編集可能なTexFileldと同じで良い。

参考: https://vuetifyjs.com/en/components/text-fields/#disabled-and-readonly

**Comment by kondoriyo** [comment]
マージしたのでcloseします
